<?php include $phireHeader; ?>
<?php if ((count($media) > 0) && $acl->isAllowed($user->role, 'media', 'search')): ?>
    <form id="asset-search-form" action="<?=$phireUri . '/media/' . $lid; ?>" method="get">
        <div><input tabindex="3" type="submit" id="submit" value="Search" /><input type="hidden" name="library_id" value="<?=$lid; ?>" /></div>
<?php if (isset($categories) && (count($categories) > 0)): ?>
        <div>
            <select name="category_id" id="category_id">
                <option value="0">----</option>
<?php foreach ($categories as $cid => $category): ?>
                <option value="<?=$cid; ?>"<?=((isset($_GET['category_id']) && ($_GET['category_id'] == $cid)) ? ' selected="selected"' : null); ?>><?=$category; ?></option>
<?php endforeach; ?>
            </select>
        </div>
<?php endif; ?>
        <div><input tabindex="1" type="text" name="title" id="title" value="<?=$searchValue; ?>" placeholder="Title" size="25" /></div>
    </form>
<?php endif; ?>
    <h1 class="media-header"><?=$title; ?></h1>
<?php if (count($media) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'media', 'add')): ?>
        <nav><a href="<?=$phireUri . '/media/add/' . $lid; ?>">+ Add</a></nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'media', 'batch')): ?>
        <nav><a href="<?=$phireUri . '/media/batch/' . $lid; ?>">Batch</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/media' . (isset($_GET['library_id']) ? '/' . (int)$_GET['library_id'] : ''); ?>">Back</a></nav>
    </nav>
<?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?>
    <form id="medias-form" action="<?=$phireUri . '/media/remove/' . $lid; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/media/' . $lid . '?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/media/' . $lid . '?sort=title';?>">Title</a></th>
                <th><a href="<?=$phireUri . '/media/' . $lid . '?sort=file';?>">Filename</a></th>
                <th class="text-center"><a href="<?=$phireUri . '/media/' . $lid . '?sort=uploaded';?>">Uploaded</a></th>
                <th class="text-center"><a href="<?=$phireUri . '/media/' . $lid . '?sort=size';?>">Size</a></th>
<?php if (isset($_GET['category_id'])): ?>
                <th>Category</th>
<?php endif; ?>
                <th class="text-center">File</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'media', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_media" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($media as $m): ?>
            <tr>
                <td><?=$m->id; ?></td>
                <td><?=$m->title; ?></td>
                <td><?=$m->file; ?></td>
                <td class="text-center"><?=date($config->datetime_format, strtotime($m->uploaded)); ?></td>
                <td class="text-center"><?=$m->filesize; ?></td>
<?php if (isset($_GET['category_id'])): ?>
                <td><?=((isset($m->category_title) && !empty($m->category_title)) ? $m->category_title : null); ?></td>
<?php endif; ?>
                <td class="text-center"><a href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $m->file; ?>" target="_blank"><img src="<?=$m->icon; ?>" height="32" /></a></td>
                <td><?php if ($acl->isAllowed($user->role, 'media', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/media/edit/' . $lid . '/' . $m->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?><input type="checkbox" name="rm_media[]" id="rm_media<?=$i++; ?>" value="<?=$m->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'media', 'add')): ?>
        <nav><a href="<?=$phireUri . '/media/add/' . $lid; ?>">+ Add</a></nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'media', 'batch')): ?>
        <nav><a href="<?=$phireUri . '/media/batch/' . $lid; ?>">Batch</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/media'; ?>">Back</a></nav>
    </nav>
    <p>There are currently no media in this library.</p>
<?php endif; ?>
<?php include $phireFooter; ?>