<?php include $phireHeader; ?>
    <h1 class="media-header"><?=$title; ?></h1>
    <div id="media-limits">
        [<span><strong>PHP Limits:</strong></span> <span>Post Max: <strong class="error"><?=ini_get('post_max_size'); ?></strong></span> | <span>Upload Max: <strong class="error"><?=$max; ?></strong></span> | <span>Max Uploads: <strong class="error"><?=ini_get('max_file_uploads'); ?></strong></span>]
    </div>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'media', 'add')): ?>
        <nav><a href="<?=$phireUri . '/media/add/' . $lid; ?>">+ Add</a></nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'media', 'batch')): ?>
        <nav><a href="<?=$phireUri . '/media/batch/' . $lid; ?>">Batch</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/media/' . $lid; ?>">Back</a></nav>
    </nav>
    <div id="drop-header">
        Having problems with the drag-and-drop batch uploader? Try the <a class="normal-link" href="<?=$phireUri . '/media/batch/' . $lid; ?>?basic=1">basic batch uploader</a>.
    </div>
    <div id="drop-zone" class="drop-zone-off" data-lid="<?=$lid; ?>">
        Drag and drop files here.
    </div>
<?php if (isset($categories) && (null !== $categories)): ?>
    <div id="batch-categories">
        <h4><?=$categories->getLabel(); ?></h4>
        <?=$categories; ?>
    </div>
<?php endif; ?>
    <div id="drop-result"<?=(isset($categories) && (null !== $categories)) ? ' class="drop-categories"' : null;?>>
    </div>
<?php include $phireFooter; ?>
