<!DOCTYPE html>
<html>

<head>

    <title><?=$systemTitle; ?> : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php if (count($assets['js']) > 0): ?>
<?php foreach ($assets['js'] as $js): ?>
    <script type="text/javascript" src="<?=$js; ?>"></script>
<?php endforeach; ?>
<?php endif; ?>

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
<?php if (count($assets['css']['link']) > 0): ?>
<?php foreach ($assets['css']['link'] as $css): ?>
    <link type="text/css" rel="stylesheet" href="<?=$css; ?>" />
<?php endforeach; ?>
<?php endif; ?>

<?php if (count($assets['css']['import']) > 0): ?>
    <style type="text/css">
<?php foreach ($assets['css']['import'] as $css): ?>
        @import url('<?=$css; ?>');
<?php endforeach; ?>
    </style>
<?php endif; ?>

    <link rel="shortcut icon" href="<?=$contentPath; ?>/assets/phire/img/phire-icon.png" type="image/png" />

<?php
    $click = ($_GET['editor'] == 'ckeditor') ?
        'window.opener.CKEDITOR.tools.callFunction(funcNum, this.href); window.close(); return false;' :
        'top.tinymce.activeEditor.windowManager.getParams().oninsert(this.href); top.tinymce.activeEditor.windowManager.close(); return false;';
?>
<?php if ($_GET['editor'] == 'ckeditor'): ?>
    <script type="text/javascript">
        function getUrlParam(paramName) {
            var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i');
            var match = window.location.search.match(reParam);
            return (match && match.length > 1) ? match[1] : '';
        }
        var funcNum = getUrlParam('CKEditorFuncNum');
    </script>
<?php endif; ?>

</head>

<body>
<div id="browser-container">
    <header>
        <h1 class="browser-title"><?=$title; ?></h1>
        <a class="logo" href="<?=$phireUri . '/media/browser?' . http_build_query($_GET); ?>">Home</a>
    </header>
    <div id="browser-content">
<?php if (isset($browserAssets) && ($_GET['asset_type'] == 'media')): ?>
    <form action="<?=$_SERVER['REQUEST_URI']; ?>" method="post" id="browser-media-form" enctype="multipart/form-data">
        <div>
            <input type="file" name="file" id="file" value="" required="required" size="30" />
            <input type="hidden" name="library_id" id="library_id" value="<?=$lid; ?>" />
            <input type="submit" name="submit" id="submit" value="Upload" />
<?php if (isset($_GET['error'])): ?>
            <br /><strong class="error">There was an error uploading the file.</strong>
<?php endif; ?>
        </div>
    </form>
<?php endif; ?>
<?php if (isset($browserAssets) && (count($browserAssets) > 0)): ?>
<?php if (isset($assetType)): ?>
        <h3><?=$assetType; ?></h3>
<?php endif; ?>
<?php if (null !== $pages): ?>
    <div class="page-links top-links"><?=$pages; ?></div>
<?php endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
<?php if ($_GET['asset_type'] == 'content'): ?>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>URI</th>
        </tr>
<?php foreach ($browserAssets as $c): ?>
        <tr>
            <td><?=$c['id']; ?></td>
            <td><?=$c['title']; ?></td>
            <td><a class="small-link" href="<?=$c['uri']; ?>" onclick="<?=$click; ?>"><?=$c['uri'] . (($c['uri'] == '/') ? ' [Index]' : null); ?></a></td>
        </tr>
<?php endforeach; ?>
<?php else: ?>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th class="text-center">File</th>
            <th>Sizes</th>
        </tr>
<?php foreach ($browserAssets as $m): ?>
        <tr>
            <td><?=$m->id; ?></td>
            <td><?=$m->title; ?></td>
            <td class="text-center"><a href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $m->file; ?>" onclick="<?=$click; ?>"><img src="<?=$m->icon; ?>" height="32" /></a></td>
            <td>
                <a class="small-link" href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $m->file; ?>" onclick="<?=$click; ?>">Original</a>
<?php if (count($sizes) > 0): ?>
<?php foreach ($sizes as $size): ?>
<?php if (file_exists($_SERVER['DOCUMENT_ROOT'] . BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $size . '/' . $m->file)): ?>
                | <a class="small-link" href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $size . '/' . $m->file; ?>" onclick="<?=$click; ?>"><?=ucwords($size); ?></a>
<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>
            </td>
        </tr>
<?php endforeach; ?>
<?php endif; ?>
    </table>
<?php elseif (isset($libraries) && (count($libraries) > 0)): ?>
<?php foreach ($libraries as $library => $types): ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th><?=$library; ?></th>
        </tr>
<?php foreach ($types as $id => $type): ?>
        <tr>
            <td><a href="<?=$phireUri . '/media/browser/' . $id . '?' . http_build_query($_GET) . '&asset=' . $_GET['type'] . '&asset_type=' . strtolower($library); ?>"><?=$type; ?></a></td>
        </tr>
<?php endforeach; ?>
    </table>
<?php endforeach; ?>
<?php else: ?>
<?php if (isset($assetType)): ?>
    <h3><?=$assetType; ?></h3>
<?php endif; ?>
    <p style="clear: both;">There are currently no assets.</p>
<?php endif; ?>
    </div>
</div>
<div id="saved"<?=(isset($saved) ? ' data-saved="1"' : null); ?>>Saved</div>
</body>

</html>