<?php include $phireHeader; ?>
    <h1 class="media-header"><?=$title; ?></h1>
    <div id="media-limits">
        [<span><strong>PHP Limits:</strong></span> <span>Post Max: <strong class="error"><?=ini_get('post_max_size'); ?></strong></span> | <span>Upload Max: <strong class="error"><?=ini_get('upload_max_filesize'); ?></strong></span> | <span>Max Uploads: <strong class="error"><?=ini_get('max_file_uploads'); ?></strong></span>]
    </div>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'media-libraries', 'add')): ?>
        <nav><a href="<?=$phireUri . '/media/libraries/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/media/libraries'; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
