<!DOCTYPE html>
<html>

<head>

    <title>Phire CMS : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php if (count($assets['js']) > 0): ?>
<?php foreach ($assets['js'] as $js): ?>
    <script type="text/javascript" src="<?=$js; ?>"></script>
<?php endforeach; ?>
<?php endif; ?>

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
<?php if (count($assets['css']['link']) > 0): ?>
<?php foreach ($assets['css']['link'] as $css): ?>
    <link type="text/css" rel="stylesheet" href="<?=$css; ?>" />
<?php endforeach; ?>
<?php endif; ?>

<?php if (count($assets['css']['import']) > 0): ?>
    <style type="text/css">
<?php foreach ($assets['css']['import'] as $css): ?>
        @import url('<?=$css; ?>');
<?php endforeach; ?>
    </style>
<?php endif; ?>

    <link rel="shortcut icon" href="<?=$contentPath; ?>/assets/phire/img/phire-icon.png" type="image/png" />

<?php
    $click = ($_GET['editor'] == 'ckeditor') ?
        'window.opener.CKEDITOR.tools.callFunction(funcNum, this.href); window.close(); return false;' :
        'top.tinymce.activeEditor.windowManager.getParams().oninsert(this.href); top.tinymce.activeEditor.windowManager.close(); return false;';
?>
<?php if ($_GET['editor'] == 'ckeditor'): ?>
    <script type="text/javascript">
        function getUrlParam(paramName) {
            var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i');
            var match = window.location.search.match(reParam);
            return (match && match.length > 1) ? match[1] : '';
        }
        var funcNum = getUrlParam('CKEditorFuncNum');
    </script>
<?php endif; ?>

</head>

<body>
<div id="browser-container">
    <header>
        <h1 class="browser-title"><?=$title; ?></h1>
        <a class="logo" href="<?=$phireUri . '/media/browser?' . http_build_query($_GET); ?>">Home</a>
    </header>
    <div id="browser-content">
<?php if (isset($media) && (count($media) > 0)): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th><a href="<?=$phireUri . '/media?sort=id';?>">#</a></th>
            <th><a href="<?=$phireUri . '/media?sort=title';?>">Title</a></th>
            <th class="text-center">File</th>
            <th>Sizes</th>
        </tr>
<?php foreach ($media as $m): ?>
        <tr>
            <td><?=$m->id; ?></td>
            <td><?=$m->title; ?></td>
            <td class="text-center"><a href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $m->file; ?>" onclick="<?=$click; ?>"><img src="<?=$m->icon; ?>" height="32" /></a></td>
            <td>
                <a class="small-link" href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $m->file; ?>" onclick="<?=$click; ?>">Original</a>
<?php if (count($sizes) > 0): ?>
<?php foreach ($sizes as $size): ?>
<?php if (file_exists($_SERVER['DOCUMENT_ROOT'] . BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $size . '/' . $m->file)): ?>
                | <a class="small-link" href="<?=BASE_PATH . CONTENT_PATH . '/' . $folder . '/' . $size . '/' . $m->file; ?>" onclick="<?=$click; ?>"><?=ucwords($size); ?></a>
<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>
            </td>
        </tr>
<?php endforeach; ?>
    </table>
<?php elseif (isset($libraries) && (count($libraries) > 0)): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th>Media Libraries</th>
        </tr>
<?php foreach ($libraries as $library): ?>
        <tr>
            <td><?php if ($acl->isAllowed($user->role, 'media-library-' . $library->id, 'index')): ?><a href="<?=$phireUri . '/media/browser/' . $library->id . '?' . http_build_query($_GET); ?>"><?=$library->name; ?></a><?php else: echo $library->name;?><?php endif; ?></td>
        </tr>
<?php endforeach; ?>
    </table>
<?php else: ?>
    <p>There are currently no media assets.</p>
<?php endif; ?>
    </div>
</div>
</body>

</html>