<?php include $phireHeader; ?>
    <h1 class="media-header"><?=$title; ?></h1>
<?php if (isset($libraries) && (count($libraries) > 0)): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th>Media Libraries</th>
        </tr>
<?php foreach ($libraries as $library): ?>
        <tr>
            <td><a href="<?=$phireUri . '/media/' . $library->id; ?>"><?=$library->name; ?></a></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php elseif (isset($media) && (count($media) > 0)): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'media', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/media/add'; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?>
    <form id="media-form" action="<?=$phireUri . '/media/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/media?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/media?sort=title';?>">Name</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'media', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_media" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($media as $m): ?>
            <tr>
                <td><?=$m->id; ?></td>
                <td><?=$m->title; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'media', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/media/edit/' . $m->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?><input type="checkbox" name="rm_media[]" id="rm_media<?=$i++; ?>" value="<?=$m->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'media', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <p>There are currently no media or media libraries.</p>
<?php endif; ?>
<?php include $phireFooter; ?>